on: push
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - "algolia"
        - "instantsearch"
        - "lannonbr"
    steps:
      - uses: actions/checkout@v2
      - run: ls | grep --exclude="${{ matrix.tag }}"
